--INSERT INTO student(major, studentName, studentNumber) VALUES ('20100123', 'Hwang Myunghan', 'ME');
--
--
--INSERT INTO course(courseNumber, professorLastName, studentNumber) VALUES ('20100123', 'Hwang Myunghan',CS,'MALE');
